### ISSUE TITLE
What is the type of element in an empty array?

### ISSUE THREAD

**Issue by iology** [bloom42/sane#19]
Are these values allowed per spec v1.0.0 (stable version?):

```
a = []
b = [[]]
c = [[],[1]]
```

I also wonder why heterogeneity is forbidden? Is it sometimes hard to implement something like `element.IsArrayOf(NUMBER)`?

**Comment by z0mbie42** [comment]
Hi, thank you to pointing out this lack of clarity. I've updated the examples ().

List heterogeneity is forbidden for v1.0 because:
* it's hard to deserialize to in strongly type languages (to which type would you deserialize `l = ["a", 1.0, 42]` in Rust for exmaple ?).
* Nobody was able to provide a clear example where list heterogeneity would be useful in a configuration format.
* Allowing list heterogeneity would introduce backward incompatibility if we then want to remove it, but not allowing it then allowing it in v1.1 (if real word use cases emerge) is backward compatible.

**Comment by iology** [comment]
The spec still doesn't make the reasoning obvious and convincing. The element type of empty inline maps and heterogeneity of inline maps are not mentioned either. So the unclear spec just makes me feel bad about this format. It is like telling me T**O**ML is not **o**bvious again. I won't bother to open a new issue because you close this issue so quickly as if there is obviously not any problem.

> it's hard to deserialize to in strongly type languages (to which type would you deserialize `l = ["a", 1.0, 42]` in Rust for exmaple ?).

I think it is just a matter of whether you are willing to use a generic container for each element. For example, `Vector<SaneValue>`, `value.is_integer()`, `value.get_integer_or(0)`, `if let SaneInteger(number) = value`. I know a schema validator can eliminate the need to implement a sum type here but I don't think this is your real concern. Please don't tell me Rust the language itself is the hindrance.

Another obvious question: why map heterogeneity is allowed and maps are not "hard to deserialize to in strongly type languages"?

According to the latest example, it seems you want to impose a schema validator, otherwise the configuration is sometimes ambiguous due to empty lists and empty maps. It's worth pointing out at the home page that this cannot be a schema-less format for some restricted parsers.

Being able to deserialize the config into a schema-less/standalone object which keeps all the essential information is definitely convenient for all kinds of processing.

> Nobody was able to provide a clear example where list heterogeneity would be useful in a configuration format.

While list heterogeneity does not seem common for configs (partly due to limited primitive types), I would like to use both integers and floats in the same list so I don't have to worry too much about number format: `[20, 20.5]`, of course the application (not necessarily the parser) will treat them all as floats for consistency. Putting something like `"20K", "5.5G", "1/3"` into the number list is not that bad as well. Just such sloppy things.

What heterogeneity means is also questionable since it is mentioned in the spec:

* Does lists of different sizes break heterogeneity?
* Does maps with different keys break heterogeneity?
* Does maps with keys of different type of values break heterogeneity?

Forbidding list heterogeneity definitely put some unnecessary burden on the parser if a schema validator is also provided.

Finally, the spec is really incomplete. Thus, a complete test suit is definitely needed before everyone can ensure there won't be compatibility issues. I can't believe this is seriously v1.0.

**Comment by z0mbie42** [comment]
> I won't bother to open a new issue because you close this issue so quickly as if there is obviously not any problem

It's common practice in the open source world when you have limited resource to handle issues, to close quickly if the maintainers (limited, after all we are humans) understanding is it's a non issue, and then reopen if they are convinced that's a real issue. Please don't take it personally.

> Another obvious question: why map heterogeneity is allowed and maps are not "hard to deserialize to in strongly type languages"?

Map heterogeneity is allowed because 90% of the time it will deserialize to a `structure`
```sane
a = {
  name = "Bart Simpson"
  age = 10
}
```
```rust
pub struct Character {
  pub name: String,
  pub age: u32,
}
```

> While list heterogeneity does not seem common for configs (partly due to limited primitive types), I would like to use both integers and floats in the same list so I don't have to worry too much about number format: [20, 20.5]

The case your are describing is a good concern but it seems more related `floats` grammar rather than to list heterogeneity. I would be happy if you propose a change about how to handle such a list with a simple (single pass) parser. But I think It's another issue. 

>  Does lists of different sizes break heterogeneity?
    Does maps with different keys break heterogeneity?
    Does maps with keys of different type of values break heterogeneity?

It's all in the spec ans examples:
* lists are not arrays so their size does not matters
* Map keys can only be `String`
* No, because a `list` of `map` is `list<map>`, not `list<map(who's elements are X)>`.

Finally it's always up to data type to which is deserialized the configuration data


> Finally, the spec is really incomplete. Thus, a complete test suit is definitely needed before everyone can ensure there won't be compatibility issues. I can't believe this is seriously v1.0.

It's my bad, it's currently not `1.0` but `1.0 beta close to finalization`. I've removed the beta indication because I should have finalized it some time ago, but another important issues took my time and I couldn't finalize it.

It will be `1.0` when a Git tag will be published.

I totally agree that a `1.0` need a test suite, but I just didn't had time yet. Contributions are welcome :)

That being said, you can consider the current spec as a 1.0 if you want to implement a parser. It seems that only disambiguation will be added.


For instance in `TOML` it seems they will also forbid heterogeneous tables for 1.0 (https://github.com/toml-lang/toml/issues/553), But it really take time and may be backward incompatible because of the wide adoption of a non finished, maybe non backward compatible spec.


What I have learned from that is it's better to start with a more restrictive spec, and then, when (and if) use cases emerge, to carefully move to a more permissive spec.


With all that being said, I truly believe that `SANE` is coherent, and easier  to use than other existing formats, and I didn't had hard time implementing a parser in Go with the current spec.

**Comment by iology** [comment]
Thanks for the answer despite my strong tone. I just wanted a more serious answer.

But still it is confusing:

*   You want to start with a more restictive spec but you didn't add enough words. So I'd rather hear the test suit.

*   You talked about compatibility with v1.1 before v1.0 is stabilized and before a test suit come out. I'm not sure if you have thought hard about all corner cases about the design. Do the public find it great and urge you to release v1.0?

*   I want your own opinions on SANE, not `*it seems* [TOML] will also ...`.

    It may not be true as you said that 90% of the time "strongly typed languages" use fixed struct(s) for maps (definitely needs a schema). But you did not tell why *it is hard* to implement something like `Map<String, Value>`. Also, strongly typed languages are not necessarily statically typed and strict like Rust.

    https://en.wikipedia.org/wiki/Strong_and_weak_typing

    <details><summary>By "strongly typed" it doesn't mean a sum type is forbidden.</summary>

    ```rust
    use std::collections::BTreeMap;

    // In Rust for a statically fixed-size recursive struct
    // we need redirection like using fixed-size pointers.
    type SaneArray = Vec<SaneValue>;
    type SaneTable = BTreeMap<String, SaneValue>;

    #[derive(PartialEq, Clone, Debug)]
    enum SaneValue {
        Boolean(bool),
        Integer(i64),
        Float(f64),
        String(String),
        Array(SaneArray),
        Table(SaneTable),
    }

    fn main() {
        let key = "Hello, world!".to_string();
        let mut items = SaneArray::new();
        let mut store = SaneTable::new();

        items.push(SaneValue::Boolean(true));
        items.push(SaneValue::Integer(42));
        items.push(SaneValue::Float(0.5));
        items.push(SaneValue::String(key.clone()));
        items.push(SaneValue::Table(store.clone()));
        store.insert(key.clone(), SaneValue::Array(items));

        if let Some(&SaneValue::Array(ref values)) = store.get(&key) {
            for v in values {
                println!("{:?}", v);
            }
        }
    }
    ```

    </details>

    This comment had explained it well but sadly some people ignored it: https://github.com/toml-lang/toml/issues/553#issuecomment-412107870

    > For statically/strongly typed language, the representation of arrays of mixed values is a solved issue: it should be represented as a sum type. So you'd have a TomlValue[] or map of TomlValue. You need to have this kind of type any way for table values, I don't see why it wouldn't be the type of array items. ...

**Comment by z0mbie42** [comment]
I believe in efficiency that's why I want to move quickly to a backward compatible 1.0. (unlike TOML which is problematic as we seen).
Then I believe that every human can make mistake that's why I prefer a more restricted, simpler approach for v1.

Finally I believe in pragmatism, if you need something come with examples where it's required, with a RFC *à la Rust* (https://github.com/rust-lang/rfcs), then we have good basis to seriously study how to proceed. Otherwise it's just a lack of focus.

**Comment by iology** [comment]
Funny, you made some decision based on random superstition "it is hard" and want me to create an RFC. This is not pragmatism but just your personal tastes.

This is just a spec, not your company product. The community will tell you when it is the real time for backward compatibility. We want to achieve some standards with the format, not to make limits for suggesting some particular programming paradigm. It is really easy to create a customized TOML for your own use.

Anyway I have got the real answer. Good luck with your flashy marketing.
